import assert from "node:assert/strict";
import test from "node:test";
import { createArticlePublishConfirmation, verifyArticlePublishConfirmation, validateClickLeaseClaims, receiptBindingFromClickLease, createInitialReceiptProjection, appendExecutionReceiptEvent, validateExecutionReceiptEvent, projectExecutionReceiptEvent } from "../app/release-control-v2.ts";
const now = new Date("2026-09-02T00:00:00.000Z"), h = x => x.repeat(64);
const binding = { receiptChainId: "chain-1", confirmationId: "confirmation-1", capabilityId: "cap-1", clickLeaseId: "lease-1", articleId: "article-1", runId: "run-1", releaseId: "release-bilibili", platform: "bilibili", artifactSha256: h("a"), packetSha256: h("b"), domContractSha256: h("c"), hostId: "host-1" };
const proj = () => ({ binding, sequence: 0, headSha256: null, hostInvocationIds: [], capabilityConsumed: false, invocationStarted: false, clickAttempts: 0, terminalResult: null, probeOnly: false });
const item = platform => ({ platform, releaseId: `release-${platform}`, buildId: "build-1", artifactSha256: h("a"), targetAccount: `owner-${platform}`, readinessSnapshotSha256: h("d") });
const ev = (eventId, eventType, hostInvocationId) => { const shapes = { capability_consumed: { writeDisposition: "continue", recoveryMode: "none", result: "not_applicable" }, click_invocation_started: { writeDisposition: "continue", recoveryMode: "none", result: "not_applicable" }, click_invoked: { writeDisposition: "stop_writes", recoveryMode: "none", result: "invoked" }, click_not_invoked: { writeDisposition: "stop_writes", recoveryMode: "none", result: "not_invoked" }, result_unknown: { writeDisposition: "freeze_writes", recoveryMode: "probe_first", result: "unknown" }, read_only_probe: { writeDisposition: "stop_writes", recoveryMode: "probe_first", result: "probe" } }; return { ...binding, eventId, eventType, hostInvocationId, observedAt: now.toISOString(), claimPromotions: [], evidenceRefs: ["evidence-1"], ...shapes[eventType] }; };
test("confirmation binds article run contract and four platforms", async () => { const items = ["zhihu", "bilibili", "maimai", "xiaohongshu"].map(item); const c = await createArticlePublishConfirmation({ confirmationId: "confirmation-1", ownerSessionId: "session-1", articleId: "article-1", runId: "run-1", contractSha256: h("f"), confirmedAt: now.toISOString(), expiresAt: "2026-09-02T00:15:00Z", items }); assert.equal((await verifyArticlePublishConfirmation(c, { articleId: "article-1", runId: "run-1", contractSha256: h("f"), items }, now)).ok, true); assert.equal((await verifyArticlePublishConfirmation({ ...c, runId: "run-2" }, undefined, now)).ok, false); await assert.rejects(() => createArticlePublishConfirmation({ ...c, items: [...items.slice(0, 3), { ...items[3], platform: "zhihu" }] })); });
test("lease fails closed for wildcard unknown and long TTL", () => { const l = { schemaVersion: "wenmai.release-control/2.0", ...binding, buildId: "build-1", targetAccount: "owner", readinessSnapshotSha256: h("d"), maxClicks: 1, issuedAt: now.toISOString(), expiresAt: "2026-09-02T00:04:00Z", nonce: "n".repeat(32) }; assert.equal(validateClickLeaseClaims(l, now).ok, true); for (const x of [{ ...l, hostId: "*" }, { ...l, targetAccount: "owner*alias" }, { ...l, targetAccount: "owner\0alias" }, { ...l, extra: true }, { ...l, expiresAt: "2026-09-02T00:06:00Z" }])
    assert.equal(validateClickLeaseClaims(x, now).ok, false); const copied = receiptBindingFromClickLease(l); assert.deepEqual(copied, binding); assert.notEqual(copied, l); const initial = createInitialReceiptProjection(l); assert.deepEqual(initial.binding, binding); assert.equal(initial.sequence, 0); assert.equal(initial.clickAttempts, 0); });
test("receipt chain rejects swaps races replay and second click", async () => { let p = proj(); const a = await appendExecutionReceiptEvent(p, ev("event-1", "capability_consumed", "invoke-1")); assert.equal((await validateExecutionReceiptEvent({ ...a, articleId: "article-2" }, p)).ok, false); p = projectExecutionReceiptEvent(p, a); assert.equal((await validateExecutionReceiptEvent(a, p)).ok, false); const b = await appendExecutionReceiptEvent(p, ev("event-2", "click_invocation_started", "invoke-2")); p = projectExecutionReceiptEvent(p, b); const c = await appendExecutionReceiptEvent(p, ev("event-3", "click_invoked", "invoke-3")); p = projectExecutionReceiptEvent(p, c); await assert.rejects(() => appendExecutionReceiptEvent(p, ev("event-4", "click_invoked", "invoke-4"))); });
test("unknown permits only probes with empty claims", async () => { let p = proj(); for (const [a, b, c] of [["event-1", "capability_consumed", "invoke-1"], ["event-2", "click_invocation_started", "invoke-2"], ["event-3", "result_unknown", "invoke-3"]]) {
    const x = await appendExecutionReceiptEvent(p, ev(a, b, c));
    p = projectExecutionReceiptEvent(p, x);
} await assert.rejects(() => appendExecutionReceiptEvent(p, ev("event-4", "click_not_invoked", "invoke-4"))); const x = await appendExecutionReceiptEvent(p, ev("event-5", "read_only_probe", "invoke-5")); assert.deepEqual(x.claimPromotions, []); assert.equal((await validateExecutionReceiptEvent({ ...x, claimPromotions: ["public"] }, p)).ok, false); });
