import type { FactoryRecipe } from "./workbench-types";
import {
  INFORMATION_COVER_RECIPE_STEP_IDS,
  INFORMATION_COVER_RECIPE_STEPS,
} from "./information-cover-workflow.ts";

export const FACTORY_RECIPES: FactoryRecipe[] = [
  {
    id: "evidence-led-longform-v1",
    version: "1.4.0",
    title: "证据驱动长文 · 标准线",
    summary: "输入委托与材料，依次形成结构、草稿、封面和平台包；每一步只说明已产生的工件，不把它写成批准、提交或公开结果。",
    topology: "sequential",
    selectionRule: "新建对外知识文章或导入选择完整生产时的默认路线。按站推进并逐项读回；单 Agent 或人工逐站推进已经足够时使用。",
    steps: [
      {
        id: "commission",
        title: "定义读者问题与委托",
        actorKind: "human",
        input: "主题、读者、已有材料、边界",
        output: "一页创作委托、写作合同（问题所有权 / 编辑模式 / 立场）与非目标",
        completionClaim: "委托已由作者确认",
      },
      {
        id: "evidence-map",
        title: "建立事实—材料账本",
        actorKind: "agent",
        writeScope: "artifact-only",
        capabilityId: "skill:write-experience-led-knowledge-article",
        input: "创作委托与本地材料",
        output: "事实、经历、推断、空缺分层账本",
        completionClaim: "账本工件已生成；事实签发仍待人工",
      },
      {
        id: "structure",
        title: "冻结编辑模式并选择主线与结构",
        actorKind: "agent",
        writeScope: "artifact-only",
        capabilityId: "skill:write-experience-led-knowledge-article",
        input: "委托、写作合同与材料账本",
        output: "可复述主线、段落职责、证据边界与反例",
        completionClaim: "结构候选已生成",
      },
      {
        id: "draft",
        title: "完成工作分支初稿",
        actorKind: "agent",
        writeScope: "branch-working-copy",
        input: "结构、证据与口吻约束",
        output: "工作副本与不可变修订",
        completionClaim: "草稿工件已创建",
      },
      {
        id: "machine-gates",
        title: "运行内置文本门禁",
        actorKind: "script",
        gateId: "builtin:text-suite-v1",
        runnerAction: "text-gates",
        input: "当前工作副本 SHA-256",
        output: "标题、结构、长句、占位符检查记录",
        completionClaim: "自动检查结果已绑定当前输入",
      },
      {
        id: "natural-chinese",
        title: "中文自然度审校",
        actorKind: "agent",
        writeScope: "artifact-only",
        capabilityId: "skill:edit-natural-chinese",
        input: "通过结构检查的草稿",
        output: "自然表达修订与问题清单",
        completionClaim: "语言修订已提交；内容事实未因此自动批准",
      },
      {
        id: "human-review",
        title: "作者审阅与签发",
        actorKind: "human",
        input: "正文、差异、门禁记录和事实账本",
        output: "批准、退回或带条件批准的决定",
        completionClaim: "人工质量决定已记录",
      },
      ...INFORMATION_COVER_RECIPE_STEPS,
      {
        id: "package",
        title: "按渠道拆分发布包",
        actorKind: "agent",
        writeScope: "artifact-only",
        dependsOn: [...INFORMATION_COVER_RECIPE_STEP_IDS],
        input: "已批准正文、四个封面工位真实 complete、v2 回执 approved/artifact_delivered 且哈希匹配的封面工件与目标渠道",
        output: "每个平台独立标题、正文、已验收封面和证据清单",
        completionClaim: "发布包已创建；不代表已提交、已发布或公开可见",
      },
    ],
  },
  {
    id: "capability-building-v1",
    version: "1.0.0",
    title: "创作能力建设 · 验证线",
    summary: "输入真实失败案例和维护责任，产出可验证的候选资产、反例与回归证据；是否采用始终由人工决定。",
    topology: "sequential",
    selectionRule: "只有真实失败样本和维护责任都已明确时使用；空白格不单独触发建设。",
    steps: [
      {
        id: "gap",
        title: "确认真实缺口",
        actorKind: "human",
        input: "失败案例、能力元素表与现有替代方案",
        output: "带范围和非目标的能力委托",
        completionClaim: "缺口由真实任务而非空白格单独证明",
      },
      {
        id: "candidate",
        title: "形成候选规则或 Skill",
        actorKind: "agent",
        writeScope: "artifact-only",
        capabilityId: "skill:codify-project-learnings",
        input: "任务证据、反例、已有资产",
        output: "candidate 资产、入口和验收标准",
        completionClaim: "候选资产已创建",
      },
      {
        id: "test",
        title: "在代表任务上对照验证",
        actorKind: "agent",
        writeScope: "artifact-only",
        input: "候选资产、基线任务与同一输入快照",
        output: "成功、失败、成本和反例记录",
        completionClaim: "测试结果可证伪且可复现",
      },
      {
        id: "adopt",
        title: "人工决定是否采用",
        actorKind: "human",
        input: "测试工件、回归入口与维护责任",
        output: "adopted / rejected 决定",
        completionClaim: "采用决定绑定证据和回归位置",
      },
    ],
  },
  {
    id: "series-fork-join-v1",
    version: "1.0.0",
    title: "系列专题 · 受控多 Agent 线",
    summary: "输入冻结委托后，三个 Agent 只产出独立研究工件；协调者裁决，再把唯一正文写入权交给一名 Agent。",
    topology: "fork-join",
    selectionRule: "仅在材料规模、视角差异或系列空槽确实带来并行收益时使用；普通单篇默认不用多 Agent。",
    steps: [
      {
        id: "series-commission",
        title: "冻结系列委托与停止条件",
        actorKind: "human",
        writeScope: "none",
        input: "系列目标、读者问题、已有文章、时间与成本上限",
        output: "版本化委托、非目标、并行理由与停止条件",
        completionClaim: "作者已确认为什么需要并行以及何时停止",
      },
      {
        id: "source-researcher",
        title: "材料与事实研究",
        actorKind: "agent",
        agentRole: "researcher",
        dependsOn: ["series-commission"],
        parallelGroup: "discovery",
        writeScope: "artifact-only",
        capabilityId: "skill:write-experience-led-knowledge-article",
        input: "冻结委托与获准材料清单",
        output: "事实—来源账本和缺证清单",
        completionClaim: "研究工件已生成；事实仍待作者签发",
      },
      {
        id: "series-analyst",
        title: "系列结构与空槽分析",
        actorKind: "agent",
        agentRole: "series-analyst",
        dependsOn: ["series-commission"],
        parallelGroup: "discovery",
        writeScope: "artifact-only",
        input: "文章库、主题候选和冻结委托",
        output: "系列槽位、重复风险和优先顺序候选",
        completionClaim: "结构候选已生成；不等于正式选题委托",
      },
      {
        id: "red-team",
        title: "反例与重复性审查",
        actorKind: "agent",
        agentRole: "critic",
        dependsOn: ["series-commission"],
        parallelGroup: "discovery",
        writeScope: "artifact-only",
        input: "委托、既有文章摘要和拟议论点",
        output: "反例、冲突、重复内容和不可证声明清单",
        completionClaim: "批判工件已生成；不替代编辑决定",
      },
      {
        id: "editorial-join",
        title: "协调者汇合并裁决冲突",
        actorKind: "human",
        dependsOn: ["source-researcher", "series-analyst", "red-team"],
        writeScope: "none",
        input: "三个独立工件及其摘要",
        output: "采用/拒绝表、主线和单篇写作合同",
        completionClaim: "冲突已逐项裁决，正文写入范围已冻结",
      },
      {
        id: "single-writer",
        title: "唯一正文 Agent 写入工作分支",
        actorKind: "agent",
        agentRole: "writer",
        dependsOn: ["editorial-join"],
        writeScope: "branch-working-copy",
        capabilityId: "skill:write-experience-led-knowledge-article",
        input: "已裁决合同、材料账本和目标分支",
        output: "工作副本与不可变修订候选",
        completionClaim: "正文工件已创建；只有该工位拥有分支写入权",
      },
      {
        id: "series-gates",
        title: "运行正文门禁与重复性复核",
        actorKind: "script",
        dependsOn: ["single-writer"],
        writeScope: "none",
        gateId: "builtin:text-suite-v1",
        input: "正文摘要、材料账本和既有文章候选",
        output: "绑定输入的门禁记录和重复风险",
        completionClaim: "技术检查已完成；人工批准仍未发生",
      },
      {
        id: "series-approval",
        title: "作者审阅、签发或退回",
        actorKind: "human",
        dependsOn: ["series-gates"],
        writeScope: "none",
        input: "正文、差异、门禁和所有 Agent 工件",
        output: "批准、退回或终止决定",
        completionClaim: "人工决定已记录，并与技术结果分离",
      },
    ],
  },
];
