"use client";
import { useCallback, useEffect, useState } from "react";
import { managementFetch } from "./management-fetch";
export type ReviewTarget = { articleId: string; projectId: string | null; packageId: string; branchId: string; revisionId: string; bodySha256: string; dirtyWorkingCopy: boolean } | null;
type Requirement = { id: string; title: string; requirementText: string; status: string; priority: string; supersedesRequirementId: string | null; lockVersion: number };
type Annotation = { id: string; requirementId: string; verdict: string; note: string; evidenceRefs: string[]; supersedesAnnotationId: string | null };
type Candidate = { id: string; sourceSetSha256: string; canonicalRuleSha256: string; candidateSha256: string; lockVersion: number; status: "candidate" | "approved" };
type Baseline = { id: string; revisionNumber: number; revisionSha256: string; candidateId: string; approvedAt: string };
const hash = (value: string) => value ? `${value.slice(0, 10)}…` : "—";
const fetchReviewData = async (articleId: string) => {
  const get = async (view: string) => { const r = await managementFetch(`/api/annotation-rsi/v1?view=${view}&articleId=${encodeURIComponent(articleId)}`); const p = await r.json(); return p.data?.items ?? []; };
  const [requirements, annotations, candidates, baselines] = await Promise.all([get("requirements"), get("annotations"), get("rule-candidates"), get("baseline-revisions")]);
  return { requirements, annotations, candidates, baselines };
};

export default function HumanReviewPanel({ target, notify, onRsiChanged }: { target: ReviewTarget; notify: (message: string) => void; onRsiChanged: () => void }) {
  const [requirements, setRequirements] = useState<Requirement[]>([]), [annotations, setAnnotations] = useState<Annotation[]>([]), [candidates, setCandidates] = useState<Candidate[]>([]), [baselines, setBaselines] = useState<Baseline[]>([]), [busy, setBusy] = useState(false);
  const [note, setNote] = useState(""), [evidence, setEvidence] = useState(""), [requirementId, setRequirementId] = useState("");
  const load = useCallback(async () => { if (!target) return; try { const data = await fetchReviewData(target.articleId); setRequirements(data.requirements); setAnnotations(data.annotations); setCandidates(data.candidates); setBaselines(data.baselines); } catch { notify("人工标注暂时无法读取。"); } }, [notify, target]);
  useEffect(() => {
    if (!target) return;
    let ignore = false;
    void fetchReviewData(target.articleId).then((data) => { if (!ignore) { setRequirements(data.requirements); setAnnotations(data.annotations); setCandidates(data.candidates); setBaselines(data.baselines); } }).catch(() => { if (!ignore) notify("人工标注暂时无法读取。"); });
    return () => { ignore = true; };
  }, [notify, target]);
  const command = async (action: string, payload: Record<string, unknown>) => { if (!target) return; setBusy(true); try { const commandId = `human:${crypto.randomUUID()}`; const r = await managementFetch("/api/annotation-rsi/v1", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, commandId, payload }) }); const p = await r.json(); if (!r.ok || p.ok === false) throw new Error(p.error?.code ?? "操作未完成"); await load(); onRsiChanged(); notify("已保存人工决定。"); } catch (error) { notify(error instanceof Error ? error.message : "操作未完成"); } finally { setBusy(false); } };
  if (!target) return null;
  if (target.dirtyWorkingCopy) return <section className="human-review-panel"><p>工作副本仍有未保存改动，请先保存为不可变版本再打标。</p></section>;
  const active = requirements.filter((item) => item.status === "accepted");
  return <section className="human-review-panel" aria-label="人工标注与 RSI"><header><span className="eyebrow">人工复核</span><h2>需求、结论与证据</h2><p>只记录人工标注及其替代历史；候选规则须经人工批准才写入不可变基线。</p></header><div className="review-grid"><section><h3>已接受需求</h3>{active.length ? active.map((item) => <article key={item.id}><strong>{item.title}</strong><p>{item.requirementText}</p><small>{item.priority} · {item.supersedesRequirementId ? `替代 ${item.supersedesRequirementId}` : "首版需求"}</small></article>) : <p>尚无已接受需求。</p>}</section><section><h3>人工标注</h3><label>关联需求<select value={requirementId} onChange={(event) => setRequirementId(event.target.value)}><option value="">请选择</option>{active.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>说明<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><label>证据（每行一项）<textarea value={evidence} onChange={(event) => setEvidence(event.target.value)} /></label><div className="review-actions">{(["pass", "fail", "inconclusive"] as const).map((verdict) => <button disabled={busy || !requirementId || !note.trim() || !evidence.trim()} key={verdict} onClick={() => void command("create_human_annotation", { articleId: target.articleId, requirementId, subjectType: "article_revision", subjectId: target.revisionId, snapshotSha256: target.bodySha256, labelSchemaVersion: 1, labelKind: "requirement_fit", verdict, severity: verdict === "fail" ? "major" : "info", note, details: {}, evidenceRefs: evidence.split("\n").map((x) => x.trim()).filter(Boolean), supersedesAnnotationId: annotations.find((a) => a.requirementId === requirementId)?.id ?? null })}>{verdict === "pass" ? "通过" : verdict === "fail" ? "失败" : "需修改"}</button>)}</div>{annotations.slice(0, 16).map((item) => <p key={item.id}><strong>{item.verdict}</strong> · {item.note} · 证据 {item.evidenceRefs.length} · {item.supersedesAnnotationId ? `替代 ${item.supersedesAnnotationId}` : "当前记录"}</p>)}</section></div><section><h3>RSI 候选摘要</h3>{candidates.slice(0, 32).map((item) => <article key={item.id}><span>{item.status === "approved" ? "已批准" : "候选"}</span> <code>{hash(item.candidateSha256)}</code>{item.status === "candidate" && <button disabled={busy} onClick={() => void command("approve_rule_candidate", { articleId: target.articleId, candidateId: item.id, expectedCanonicalRuleSha256: item.canonicalRuleSha256, expectedCandidateSha256: item.candidateSha256, expectedLockVersion: item.lockVersion, expectedSourceSetSha256: item.sourceSetSha256, expectedHeadRevisionId: baselines[0]?.id ?? null, expectedHeadRevisionSha256: baselines[0]?.revisionSha256 ?? null, note: "人工批准" })}>批准并建立基线</button>}</article>) || <p>暂无候选。</p>}</section><section><h3>不可变基线</h3>{baselines.slice(0, 16).map((item) => <p key={item.id}>#{item.revisionNumber} · {hash(item.revisionSha256)} · 来自 {item.candidateId} · {item.approvedAt}</p>) || <p>尚未建立基线。</p>}</section></section>;
}
