import { spawn, spawnSync } from "node:child_process";
import { createHash, randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import process from "node:process";

export const WENMAI_CANONICAL_HOST = "::1";
export const WENMAI_CANONICAL_PORT = "3000";
export const WENMAI_CANONICAL_ORIGIN = "http://[::1]:3000";
export const WENMAI_AUTH_PROBE_URL = `${WENMAI_CANONICAL_ORIGIN}/api/auth`;
export const WENMAI_LOCAL_IMPORT_ENDPOINT = `${WENMAI_CANONICAL_ORIGIN}/api/local-import/v1`;
export class WenmaiLauncherError extends Error { constructor(code,message) { super(message); this.name="WenmaiLauncherError"; this.code=code; } }
export function parseRunArguments(argv) { const command=argv[0]??"dev", rest=argv.slice(1), unknown=rest.filter(x=>x!=="--open"), isServing=command==="dev"||command==="start", openRequested=rest.includes("--open"); if(unknown.length) throw new WenmaiLauncherError("UNKNOWN_LAUNCHER_ARGUMENT",`不支持的文脉启动参数：${unknown.join(" ")}`); if(openRequested&&!isServing) throw new WenmaiLauncherError("OPEN_REQUIRES_SERVER","--open 只能用于 dev 或 start 服务命令"); return {command,isServing,openRequested}; }
export function isWenmaiAuthEnvelope(payload) { return Boolean(payload?.ok===true&&typeof payload.requestId==="string"&&payload.requestId.startsWith("auth-request-")&&payload.data?.canonicalOrigin===WENMAI_CANONICAL_ORIGIN&&typeof payload.data?.authenticated==="boolean"&&typeof payload.data?.pairing?.available==="boolean"); }
export async function probeWenmaiInstance({fetchImpl=globalThis.fetch,timeoutMs=800}={}) { const ctl=new AbortController(), timer=setTimeout(()=>ctl.abort(),timeoutMs); try { const response=await fetchImpl(WENMAI_AUTH_PROBE_URL,{headers:{accept:"application/json"},cache:"no-store",signal:ctl.signal}); if(response.status!==200||!/^application\/json\b/iu.test(response.headers.get("content-type")??"")) return {state:"occupied",reason:`HTTP ${response.status}`}; try {const payload=await response.json();return isWenmaiAuthEnvelope(payload)?{state:"healthy",payload}:{state:"occupied",reason:"unexpected-json"};}catch{return {state:"occupied",reason:"invalid-json"};} } catch(error) { return error?.code==="ECONNREFUSED"||error?.cause?.code==="ECONNREFUSED"?{state:"absent"}:{state:"occupied",reason:error instanceof Error?error.message:"probe-failed"}; } finally {clearTimeout(timer);} }
export function persistLocalImportCredential({environment,cwd,platform,credential,spawnSyncImpl=spawnSync}) { if(platform!=="win32") throw new WenmaiLauncherError("LOCAL_IMPORT_DPAPI_UNAVAILABLE","本机免配对导入目前只支持 Windows DPAPI CurrentUser"); if(!environment.LOCALAPPDATA) throw new WenmaiLauncherError("LOCAL_IMPORT_STATE_UNAVAILABLE","LOCALAPPDATA 不可用，无法安全保存本机导入凭据"); const output=join(environment.LOCALAPPDATA,"WenmaiStudio","local-import-operator.dpapi"), shell=join(environment.SystemRoot||environment.SYSTEMROOT||"C:\\Windows","System32","WindowsPowerShell","v1.0","powershell.exe"); const result=spawnSyncImpl(shell,["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",join(cwd,"scripts","set-wenmai-local-import-credential.ps1"),"-OutputPath",output],{input:JSON.stringify(credential),encoding:"utf8",windowsHide:true,env:environment});if(result.error||result.status!==0)throw new WenmaiLauncherError("LOCAL_IMPORT_CREDENTIAL_WRITE_FAILED","本机导入凭据写入失败");return {credentialPath:output}; }
export function createRuntimeAuthentication(environment,stdout,{cwd=process.cwd(),platform=process.platform,persistLocalImportCredentialImpl=persistLocalImportCredential}={}) {const bootId=`management-boot-${randomBytes(16).toString("base64url")}`,code=`wenmai1.${randomBytes(16).toString("base64url")}.${randomBytes(16).toString("base64url")}`, expiresAt=new Date(Date.now()+300000);Object.assign(environment,{WENMAI_AUTH_CANONICAL_ORIGIN:WENMAI_CANONICAL_ORIGIN,WENMAI_AUTH_BOOT_ID:bootId,WENMAI_AUTH_CHALLENGE_ID:`management-challenge-${randomBytes(12).toString("base64url")}`,WENMAI_AUTH_PAIRING_SHA256:createHash("sha256").update(code).digest("hex"),WENMAI_AUTH_CHALLENGE_CREATED_AT:new Date().toISOString(),WENMAI_AUTH_CHALLENGE_EXPIRES_AT:expiresAt.toISOString(),WENMAI_AUTH_CSRF_HMAC_KEY:randomBytes(32).toString("base64url"),WENMAI_PUBLISH_CAPABILITY_HMAC_KEY:randomBytes(32).toString("base64url"),WENMAI_RELEASE_CONTROL_V2_HOST_HMAC_KEY:randomBytes(32).toString("base64url")});const token=`wenmai_local_import_${randomBytes(32).toString("base64url")}`,localBoot=`local-import-boot-${randomBytes(16).toString("base64url")}`;Object.assign(environment,{WENMAI_LOCAL_IMPORT_CANONICAL_ORIGIN:WENMAI_CANONICAL_ORIGIN,WENMAI_LOCAL_IMPORT_BOOT_ID:localBoot,WENMAI_LOCAL_IMPORT_TOKEN_SHA256:createHash("sha256").update(token).digest("hex")});persistLocalImportCredentialImpl({environment,cwd,platform,credential:{schemaVersion:1,canonicalOrigin:WENMAI_CANONICAL_ORIGIN,endpoint:WENMAI_LOCAL_IMPORT_ENDPOINT,bootId:localBoot,token,createdAt:new Date().toISOString()}});stdout.write(`\n文脉只监听本机：${WENMAI_CANONICAL_ORIGIN}\n备用一次性管理配对码：${code}\n`);return bootId;}
const delay=(ms)=>new Promise(resolve=>setTimeout(resolve,ms));
export async function waitForHealthyWenmai({probeImpl=probeWenmaiInstance,expectedBootId="",timeoutMs=30000,intervalMs=250,sleepImpl=delay}={}) {const end=Date.now()+timeoutMs;let last={state:"absent"};while(Date.now()<end){last=await probeImpl();if(last.state==="healthy"){if(!expectedBootId||last.payload?.data?.bootId===expectedBootId)return last;throw new WenmaiLauncherError("STARTUP_BOOT_MISMATCH","另一轮文脉启动占用了本机端口");}await sleepImpl(intervalMs);}throw new WenmaiLauncherError("STARTUP_HEALTH_TIMEOUT",`文脉未通过 ${WENMAI_AUTH_PROBE_URL} 健康检查（${last.state}）`);}
export async function openWenmaiInWindows({spawnImpl=spawn,platform=process.platform}={}) {if(platform!=="win32")throw new WenmaiLauncherError("WINDOWS_OPEN_UNAVAILABLE","自动打开目前只支持 Windows；请手动打开固定本机地址");await new Promise((resolve,reject)=>{const child=spawnImpl("explorer.exe",[WENMAI_CANONICAL_ORIGIN],{detached:true,stdio:"ignore",windowsHide:true});child.once("error",reject);child.once("spawn",()=>{child.unref?.();resolve();});});}
function childLifecycle(child){return new Promise(resolve=>{child.once("error",error=>resolve({kind:"error",error}));child.once("exit",(code,signal)=>resolve({kind:"exit",code,signal}));});}
function assertNoMaintenanceLock(cwd){if(existsSync(join(cwd,".wenmai-runtime-maintenance.lock")))throw new WenmaiLauncherError("MAINTENANCE_LOCK_ACTIVE","刷新维护锁仍在；拒绝启动文脉服务");}
export async function runVinext({argv=process.argv.slice(2),environment=process.env,cwd=process.cwd(),platform=process.platform,stdout=process.stdout,stderr=process.stderr,spawnImpl=spawn,probeImpl=probeWenmaiInstance,waitForHealthyImpl=waitForHealthyWenmai,openImpl=openWenmaiInWindows,persistLocalImportCredentialImpl=persistLocalImportCredential}={}) {const {command,isServing,openRequested}=parseRunArguments(argv);if(isServing){assertNoMaintenanceLock(cwd);const existing=await probeImpl();if(existing.state==="healthy"){if(!openRequested)throw new WenmaiLauncherError("WENMAI_ALREADY_RUNNING",`文脉已经在 ${WENMAI_CANONICAL_ORIGIN} 运行`);await openImpl({spawnImpl,platform});return {kind:"existing",opened:true};}if(existing.state!=="absent")throw new WenmaiLauncherError("PORT_OCCUPIED_NON_WENMAI",`${WENMAI_CANONICAL_ORIGIN} 已有响应；不会结束或覆盖该进程。`);}const env={...environment,WRANGLER_LOG_PATH:environment.WRANGLER_LOG_PATH??".wrangler/wrangler.log"},args=[command];let bootId="";if(isServing){bootId=createRuntimeAuthentication(env,stdout,{cwd,platform,persistLocalImportCredentialImpl});args.push("--hostname",WENMAI_CANONICAL_HOST,"--port",WENMAI_CANONICAL_PORT);}const file=platform==="win32"?".\\node_modules\\.bin\\vinext.cmd":"./node_modules/.bin/vinext",child=spawnImpl(file,args,{cwd,stdio:"inherit",shell:platform==="win32",env}),lifecycle=childLifecycle(child);let opened=false;if(isServing&&openRequested){const result=await Promise.race([Promise.resolve(waitForHealthyImpl({probeImpl,expectedBootId:bootId})).then(()=>({kind:"ready"}),error=>({kind:"failed",error})),lifecycle]);if(result.kind==="ready"){try{await openImpl({spawnImpl,platform});opened=true;stdout.write(`文脉已就绪并打开：${WENMAI_CANONICAL_ORIGIN}\n`);}catch(error){stderr.write(`文脉已就绪，但无法自动打开浏览器：${error.message}\n`);}}}return {kind:"started",child,lifecycle,opened};}
export async function runVinextEntrypoint(dependencies={}) {const result=await runVinext(dependencies);if(!result.lifecycle)return {result,outcome:null,exitCode:0,signal:null};const outcome=await result.lifecycle;return {result,outcome,exitCode:outcome.kind==="error"?1:(outcome.code??1),signal:outcome.signal??null};}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  runVinextEntrypoint().then(({ exitCode, signal }) => {
    if (signal) process.kill(process.pid, signal);
    else process.exitCode = exitCode;
  }).catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
